import ImageEditor from '@/components/ImageEditor';
import ImageGallery from '@/components/ImageGallery';
import ImagePreviewOverlay from '@/components/ImagePreviewOverlay';
import FeaturedCardInfo from '@/components/FeaturedCardInfo';
// import { Heart } from 'lucide-react';
import HeroSlidesModal from '@/components/modals/HeroSlidesModal';
import FeaturedPropertiesModal from '@/components/modals/FeaturedPropertiesModal';
import SlideCard from '@/components/SlideCard';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { cn } from '@/lib/utils';
import HeaderStandalone from '@/main/components/ui/HeaderStandalone';
import type { BreadcrumbItem } from '@/types';
import { Head } from '@inertiajs/react';
import { apiFetch } from '@/lib/api';
import { useEffect, useState } from 'react';
import '../../css/oldsite.css';

// Typed route helpers generated by Wayfinder
import * as FeaturedActions from '@/actions/App/Http/Controllers/FeaturedPropertyController';
import * as HeroActions from '@/actions/App/Http/Controllers/HeroSlideController';
import * as ImageActions from '@/actions/App/Http/Controllers/ImageController';

type Image = {
    id: number;
    url: string;
    original_name: string;
    filename: string;
    width?: number | null;
    height?: number | null;
};

type HeroSlide = {
    id: number;
    image_id: number;
    image_url?: string | null;
    title: string;
    subtitle?: string | null;
    price: string;
    bedrooms?: number | null;
    bathrooms?: number | null;
    area?: string | null;
    neighborhood?: string | null;
    is_new?: boolean;
    is_published?: boolean;
    position?: number;
};

type FeaturedProperty = {
    id: number;
    image_id: number;
    image_url?: string | null;
    title: string;
    neighborhood?: string | null;
    price: string;
    bedrooms?: number | null;
    bathrooms?: number | null;
    area?: string | null;
    type?: string | null;
    features?: string[];
    price_range?: string | null;
    is_new?: boolean;
    is_published?: boolean;
    position?: number;
};

const breadcrumbs: BreadcrumbItem[] = [{ title: 'Painel', href: '/painel' }];

// api helpers moved to '@/lib/api'

export default function Painel() {
    // Imagens
    const [images, setImages] = useState<Image[]>([]);
    const [isUploading, setIsUploading] = useState(false);
    const [files, setFiles] = useState<FileList | null>(null);

    // Slides
    const [slides, setSlides] = useState<HeroSlide[]>([]);
    const [imagesLoading, setImagesLoading] = useState(false);
    const [slidesLoading, setSlidesLoading] = useState(false);
    const [editingSlide, setEditingSlide] = useState<HeroSlide | null>(null);
    // Local state for legacy slide modal
    const [creatingSlide, setCreatingSlide] = useState(false);
    const [newSlide, setNewSlide] = useState<Partial<HeroSlide>>({});
    const [selectedSlideImage, setSelectedSlideImage] = useState<Image | null>(null);
    const [editedSlideBlob, setEditedSlideBlob] = useState<Blob | null>(null);

    // Destaques
    const [featured, setFeatured] = useState<FeaturedProperty[]>([]);

    const [dragging, setDragging] = useState<{ type: 'slide' | 'featured'; id: number } | null>(null);
    const [slideOrderDirty, setSlideOrderDirty] = useState(false);
    const [featuredOrderDirty, setFeaturedOrderDirty] = useState(false);

    const [heroModalOpen, setHeroModalOpen] = useState(false);
    const [featuredModalOpen, setFeaturedModalOpen] = useState(false);
    const [imagePickerOpen, setImagePickerOpen] = useState(false);
    const [imagePickerFor, setImagePickerFor] = useState<'slide' | null>(null);

    // Notices
    const [notice, setNotice] = useState<{ type: 'success' | 'error'; title: string; message?: string } | null>(null);
    // Tabs: imagens | publicacoes
    const [tab, setTab] = useState<'images' | 'publicacoes'>('publicacoes');

    useEffect(() => {
        refreshAll();
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    // Garante tema claro nesta tela (evita fundo preto do modo dark)
    useEffect(() => {
        try {
            document.documentElement.classList.remove('dark');
        } catch {}
    }, []);

    // Masks and formatters
    const formatCurrencyBRLInput = (value: string) => {
        const digits = value.replace(/\D/g, '');
        if (!digits) return '';
        const number = Number(digits) / 100;
        try {
            return number.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
        } catch {
            return `R$ ${number.toFixed(2)}`;
        }
    };

    const formatAreaM2Input = (value: string) => {
        // Mantém apenas dígitos e formata com separador de milhar (pt-BR)
        const digits = value.replace(/\D/g, '');
        if (!digits) return '';
        const n = parseInt(digits, 10);
        try {
            return `${n.toLocaleString('pt-BR')} m²`;
        } catch {
            // Fallback simples
            return `${n} m²`;
        }
    };

    const refreshAll = async () => {
        await Promise.all([refreshImages(), refreshSlides(), refreshFeatured()]);
    };

    const refreshImages = async () => {
        setImagesLoading(true);
        try {
            const data = await apiFetch<Image[]>(ImageActions.index());
            setImages(data);
        } catch (e) {
            setNotice({ type: 'error', title: 'Falha ao carregar imagens', message: e instanceof Error ? e.message : String(e) });
        } finally {
            setImagesLoading(false);
        }
    };

    const refreshSlides = async () => {
        setSlidesLoading(true);
        try {
            const data = await apiFetch<HeroSlide[]>(HeroActions.index());
            setSlides(data);
        } catch (e) {
            setNotice({ type: 'error', title: 'Falha ao carregar slides', message: e instanceof Error ? e.message : String(e) });
        } finally {
            setSlidesLoading(false);
        }
    };

    const refreshFeatured = async () => {
        try {
            const data = await apiFetch<FeaturedProperty[]>(FeaturedActions.index());
            setFeatured(data);
        } catch (e) {
            setNotice({ type: 'error', title: 'Falha ao carregar destaques', message: e instanceof Error ? e.message : String(e) });
        }
    };

    const onUpload = async () => {
        if (!files || files.length === 0) return;
        const fd = new FormData();
        Array.from(files).forEach((f) => fd.append('images[]', f));
        setIsUploading(true);
        try {
            await apiFetch(ImageActions.store(), { body: fd });
            setFiles(null);
            await refreshImages();
            setNotice({ type: 'success', title: 'Imagens enviadas com sucesso' });
        } finally {
            setIsUploading(false);
        }
    };

    const deleteImage = async (id: number) => {
        if (!confirm('Excluir esta imagem?')) return;
        await apiFetch(ImageActions.destroy(id));
        await refreshImages();
    };

    const submitSlide = async () => {
        if (!selectedSlideImage?.id || !newSlide.title || !newSlide.price) {
            alert('Selecione uma imagem, título e preço.');
            return;
        }
        setCreatingSlide(true);
        try {
            let image_id = selectedSlideImage.id;
            if (editedSlideBlob) {
                const fd = new FormData();
                fd.append('images[]', editedSlideBlob, 'preview-editada.png');
                const uploaded = await apiFetch<Image[]>(ImageActions.store(), { body: fd });
                if (uploaded[0]?.id) image_id = uploaded[0].id;
            }
            const body = JSON.stringify({
                image_id,
                title: newSlide.title,
                subtitle: newSlide.subtitle ?? null,
                price: newSlide.price,
                bedrooms: newSlide.bedrooms ?? null,
                bathrooms: newSlide.bathrooms ?? null,
                area: newSlide.area ?? null,
                neighborhood: newSlide.neighborhood ?? null,
                is_new: !!newSlide.is_new,
                is_published: !!newSlide.is_published,
            });
            if (newSlide.id) {
                await apiFetch(HeroActions.update({ heroSlide: newSlide.id }), {
                    body,
                    headers: { 'Content-Type': 'application/json' },
                });
                setNotice({ type: 'success', title: 'Slide atualizado' });
            } else {
                await apiFetch(HeroActions.store(), {
                    body,
                    headers: { 'Content-Type': 'application/json' },
                });
                setNotice({ type: 'success', title: 'Slide adicionado' });
            }
            setNewSlide({});
            setSelectedSlideImage(null);
            setEditedSlideBlob(null);
            await refreshSlides();
        } finally {
            setCreatingSlide(false);
        }
    };

    const toggleSlidePublish = async (id: number) => {
        await apiFetch(HeroActions.togglePublish({ heroSlide: id }));
        await refreshSlides();
    };

    const deleteSlide = async (id: number) => {
        if (!confirm('Excluir este slide?')) return;
        await apiFetch(HeroActions.destroy({ heroSlide: id }));
        await refreshSlides();
    };

    const editSlide = (slide: HeroSlide) => {
        setEditingSlide(slide);
        setHeroModalOpen(true);
    };

    const toggleFeaturedPublish = async (id: number) => {
        await apiFetch(FeaturedActions.togglePublish({ featuredProperty: id }));
        await refreshFeatured();
    };

    const deleteFeatured = async (id: number) => {
        if (!confirm('Excluir este destaque?')) return;
        await apiFetch(FeaturedActions.destroy({ featuredProperty: id }));
        await refreshFeatured();
    };

    const reorderList = <T extends { id: number }>(list: T[], sourceId: number, targetId: number): T[] | null => {
        const next = list.slice();
        const fromIndex = next.findIndex((item) => item.id === sourceId);
        const toIndex = next.findIndex((item) => item.id === targetId);
        if (fromIndex === -1 || toIndex === -1 || fromIndex === toIndex) return null;
        const [moved] = next.splice(fromIndex, 1);
        next.splice(toIndex, 0, moved);
        return next;
    };

    const persistSlidesOrder = async () => {
        const ids = slides.map((s) => s.id);
        if (ids.length === 0) return;
        try {
            await apiFetch(HeroActions.reorder.patch(), {
                body: JSON.stringify({ ids }),
                headers: { 'Content-Type': 'application/json' },
            });
        } catch (e) {
            setNotice({
                type: 'error',
                title: 'Falha ao reordenar slides',
                message: e instanceof Error ? e.message : String(e),
            });
            await refreshSlides();
        } finally {
            setSlideOrderDirty(false);
        }
    };

    const persistFeaturedOrder = async () => {
        const ids = featured.map((f) => f.id);
        if (ids.length === 0) return;
        try {
            await apiFetch(FeaturedActions.reorder.patch(), {
                body: JSON.stringify({ ids }),
                headers: { 'Content-Type': 'application/json' },
            });
        } catch (e) {
            setNotice({
                type: 'error',
                title: 'Falha ao reordenar destaques',
                message: e instanceof Error ? e.message : String(e),
            });
            await refreshFeatured();
        } finally {
            setFeaturedOrderDirty(false);
        }
    };

    const handleDragEnd = async () => {
        if (!dragging) return;
        const currentDrag = dragging;
        setDragging(null);
        if (currentDrag.type === 'slide') {
            if (slideOrderDirty) await persistSlidesOrder();
        } else if (currentDrag.type === 'featured') {
            if (featuredOrderDirty) await persistFeaturedOrder();
        }
    };

    return (
        <div className="old-site">
            <Head title="Painel" />
            <HeaderStandalone />

            <div className="container-responsive section-spacing flex flex-col gap-6 pt-6">
                {notice && (
                    <Alert variant={notice.type === 'error' ? 'destructive' : 'default'}>
                        <AlertTitle>{notice.title}</AlertTitle>
                        {notice.message && <AlertDescription>{notice.message}</AlertDescription>}
                    </Alert>
                )}
                {/* Tabs */}
                <div className="mb-4 border-b">
                    <div className="flex gap-2">
                        <button
                            type="button"
                            onClick={() => setTab('publicacoes')}
                            className={`-mb-px border-b-2 px-4 py-2 ${tab === 'publicacoes' ? 'border-primary text-primary' : 'border-transparent text-muted-foreground hover:text-foreground'}`}
                        >
                            Publicações
                        </button>
                        <button
                            type="button"
                            onClick={() => setTab('images')}
                            className={`-mb-px border-b-2 px-4 py-2 ${tab === 'images' ? 'border-primary text-primary' : 'border-transparent text-muted-foreground hover:text-foreground'}`}
                        >
                            Imagens
                        </button>
                    </div>
                </div>
                {/* Imagens */}
                {tab === 'images' && (
                    <Card>
                        <CardHeader>
                            <CardTitle>Gerenciar Imagens</CardTitle>
                        </CardHeader>
                        <CardContent className="space-y-4">
                            <div className="flex flex-col gap-2 sm:flex-row sm:items-end">
                                <div className="flex-1">
                                    <Label htmlFor="images">Enviar imagens (até 20 por vez)</Label>
                                    <Input id="images" type="file" multiple accept="image/*" onChange={(e) => setFiles(e.target.files)} />
                                </div>
                                <div>
                                    <Button onClick={onUpload} disabled={isUploading || !files || files.length === 0}>
                                        {isUploading ? 'Enviando…' : 'Enviar'}
                                    </Button>
                                </div>
                            </div>

                            {images.length > 0 ? (
                                <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6">
                                    {images.map((img) => (
                                        <div key={img.id} className="group relative overflow-hidden rounded-md border">
                                            <img src={img.url} alt={img.original_name} className="h-36 w-full object-cover" />
                                            <div className="absolute inset-x-0 bottom-0 flex items-center justify-between bg-black/50 p-1 text-xs text-white opacity-0 transition group-hover:opacity-100">
                                                <span className="truncate" title={img.original_name}>
                                                    {img.original_name}
                                                </span>
                                                <button className="rounded bg-red-600 px-2 py-0.5 text-[11px]" onClick={() => deleteImage(img.id)}>
                                                    Excluir
                                                </button>
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            ) : (
                                <p className="text-sm text-muted-foreground">Nenhuma imagem enviada ainda.</p>
                            )}
                        </CardContent>
                    </Card>
                )}

                {/* Hero Slides */}
                {tab === 'publicacoes' && (
                    <>
                        {/* Seção: Hero Slides */}
                        <div className="mb-2 flex flex-wrap items-center justify-between gap-2">
                            <div className="flex items-center gap-2">
                                <h2 className="text-lg font-semibold">Hero Slides</h2>
                                <Button className="w-auto" onClick={() => setHeroModalOpen(true)}>
                                    Novo Slide
                                </Button>
                            </div>
                            {/* Botão de atualizar removido */}
                        </div>

                        <div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
                            {slides.map((s) => (
                                <div
                                    key={s.id}
                                    draggable
                                    onDragStart={(event) => {
                                        event.dataTransfer.effectAllowed = 'move';
                                        event.dataTransfer.setData('text/plain', String(s.id));
                                        setDragging({ type: 'slide', id: s.id });
                                    }}
                                    onDragEnter={() => {
                                        if (!dragging || dragging.type !== 'slide' || dragging.id === s.id) return;
                                        setSlides((prev) => {
                                            const updated = reorderList(prev, dragging.id, s.id);
                                            if (!updated) return prev;
                                            setSlideOrderDirty(true);
                                            return updated;
                                        });
                                    }}
                                    onDragOver={(event) => {
                                        if (!dragging || dragging.type !== 'slide') return;
                                        event.preventDefault();
                                        event.dataTransfer.dropEffect = 'move';
                                    }}
                                    onDrop={(event) => {
                                        if (!dragging || dragging.type !== 'slide') return;
                                        event.preventDefault();
                                    }}
                                    onDragEnd={handleDragEnd}
                                    className={cn(
                                        'cursor-move select-none',
                                        dragging?.type === 'slide' && dragging.id === s.id ? 'ring-2 ring-primary ring-offset-2' : '',
                                    )}
                                >
                                    <SlideCard slide={s} onEdit={editSlide} onToggle={toggleSlidePublish} onDelete={deleteSlide} />
                                </div>
                            ))}
                        </div>

                        {/* Seção: Imóveis em Destaque */}
                        <div className="mt-10 mb-2 flex flex-wrap items-center justify-between gap-2">
                            <div className="flex items-center gap-2">
                                <h2 className="text-lg font-semibold">Imóveis em Destaque</h2>
                                <Button className="w-auto" onClick={() => setFeaturedModalOpen(true)}>
                                    Novo Destaque
                                </Button>
                            </div>
                            {/* Botão de atualizar removido */}
                        </div>
                        <div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
                            {featured.map((f) => (
                                <div
                                    key={f.id}
                                    draggable
                                    onDragStart={(event) => {
                                        event.dataTransfer.effectAllowed = 'move';
                                        event.dataTransfer.setData('text/plain', String(f.id));
                                        setDragging({ type: 'featured', id: f.id });
                                    }}
                                    onDragEnter={() => {
                                        if (!dragging || dragging.type !== 'featured' || dragging.id === f.id) return;
                                        setFeatured((prev) => {
                                            const updated = reorderList(prev, dragging.id, f.id);
                                            if (!updated) return prev;
                                            setFeaturedOrderDirty(true);
                                            return updated;
                                        });
                                    }}
                                    onDragOver={(event) => {
                                        if (!dragging || dragging.type !== 'featured') return;
                                        event.preventDefault();
                                        event.dataTransfer.dropEffect = 'move';
                                    }}
                                    onDrop={(event) => {
                                        if (!dragging || dragging.type !== 'featured') return;
                                        event.preventDefault();
                                    }}
                                    onDragEnd={handleDragEnd}
                                    className={cn(
                                        'property-card bg-white rounded-2xl shadow-lg overflow-hidden cursor-move select-none',
                                        dragging?.type === 'featured' && dragging.id === f.id
                                            ? 'ring-2 ring-primary ring-offset-2'
                                            : '',
                                    )}
                                >
                                    <div className="relative">
                                        <div className="h-64 overflow-hidden">
                                            {f.image_url ? (
                                                <img
                                                    src={f.image_url}
                                                    alt={f.title}
                                                    className="h-full w-full object-cover transition-transform duration-300 hover:scale-105"
                                                />
                                            ) : (
                                                <div className="h-full w-full bg-muted" />
                                            )}
                                        </div>
                                        <div className="absolute left-4 top-4 flex gap-2">
                                            {!!f.is_new && (
                                                <span className="rounded-full bg-primary px-3 py-1 text-xs font-semibold text-white">Novo</span>
                                            )}
                                            {(f.neighborhood ?? '').toString().trim() && (
                                                <span className="rounded-full bg-white/90 px-3 py-1 text-xs font-medium text-gray-900 backdrop-blur-sm">
                                                    {f.neighborhood}
                                                </span>
                                            )}
                                        </div>
                                        {/* Botão de favorito removido */}
                                    </div>
                                    <FeaturedCardInfo
                                        title={f.title}
                                        neighborhood={f.neighborhood}
                                        bedrooms={f.bedrooms as any}
                                        bathrooms={f.bathrooms as any}
                                        area={f.area ?? undefined}
                                        features={Array.isArray(f.features) ? (f.features as string[]) : []}
                                        price={f.price}
                                    />
                                </div>
                            ))}
                        </div>

                        <Dialog open={heroModalOpen} onOpenChange={setHeroModalOpen}>
                            <DialogContent className="w-full sm:max-w-5xl" aria-describedby="hero-slides-desc">
                                <DialogHeader>
                                    <div className="flex items-center justify-between">
                                        <DialogTitle>Hero Slides</DialogTitle>
                                        <div className="flex items-center gap-2 text-sm text-muted-foreground">
                                            <span>{slidesLoading ? 'Carregando…' : `${slides.length} itens`}</span>
                                            <Button
                                                className="w-auto hidden"
                                                variant="secondary"
                                                onClick={refreshSlides}
                                                disabled={slidesLoading}
                                                title="Atualizar"
                                            >
                                                ↻
                                            </Button>
                                        </div>
                                    </div>
                                </DialogHeader>
                                <DialogDescription id="hero-slides-desc">
                                    Preencha os dados e selecione uma imagem para criar ou editar um slide do hero.
                                </DialogDescription>
                                <div className="space-y-4">
                                    <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-4">
                                        <div>
                                            <Label>Título</Label>
                                            <Input
                                                value={newSlide.title ?? ''}
                                                onChange={(e) => setNewSlide((s) => ({ ...s, title: e.target.value }))}
                                                placeholder="Ex: Casa moderna no Setor Marista"
                                            />
                                        </div>
                                        <div>
                                            <Label>Subtítulo</Label>
                                            <Input
                                                value={newSlide.subtitle ?? ''}
                                                onChange={(e) => setNewSlide((s) => ({ ...s, subtitle: e.target.value }))}
                                                placeholder="Ex: Próximo ao Flamboyant"
                                            />
                                        </div>
                                        <div>
                                            <Label>Bairro</Label>
                                            <Input
                                                value={newSlide.neighborhood ?? ''}
                                                onChange={(e) => setNewSlide((s) => ({ ...s, neighborhood: e.target.value }))}
                                                placeholder="Ex: Setor Marista"
                                            />
                                        </div>
                                        <div>
                                            <Label>Preço</Label>
                                            <Input
                                                value={newSlide.price ?? ''}
                                                onChange={(e) => setNewSlide((s) => ({ ...s, price: formatCurrencyBRLInput(e.target.value) }))}
                                                inputMode="numeric"
                                                placeholder="Ex: R$ 1.250.000,00"
                                            />
                                        </div>
                                    </div>
                                    <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
                                        <div>
                                            <Label>Quartos</Label>
                                            <Input
                                                type="number"
                                                min={0}
                                                value={newSlide.bedrooms ?? ''}
                                                onChange={(e) => setNewSlide((s) => ({ ...s, bedrooms: Number(e.target.value || 0) }))}
                                                inputMode="numeric"
                                                placeholder="Ex: 3"
                                            />
                                        </div>
                                        <div>
                                            <Label>Banheiros</Label>
                                            <Input
                                                type="number"
                                                min={0}
                                                value={newSlide.bathrooms ?? ''}
                                                onChange={(e) => setNewSlide((s) => ({ ...s, bathrooms: Number(e.target.value || 0) }))}
                                                inputMode="numeric"
                                                placeholder="Ex: 2"
                                            />
                                        </div>
                                        <div>
                                            <Label>Área</Label>
                                            <Input
                                                value={newSlide.area ?? ''}
                                                onChange={(e) => setNewSlide((s) => ({ ...s, area: formatAreaM2Input(e.target.value) }))}
                                                inputMode="numeric"
                                                placeholder="Ex: 120 m²"
                                            />
                                        </div>
                                    </div>
                                    <div className="flex items-center gap-6">
                                        <label className="flex items-center gap-2 text-sm">
                                            <input
                                                type="checkbox"
                                                checked={!!newSlide.is_new}
                                                onChange={(e) => setNewSlide((s) => ({ ...s, is_new: e.target.checked }))}
                                            />
                                            Novo
                                        </label>
                                        <label className="flex items-center gap-2 text-sm">
                                            <input
                                                type="checkbox"
                                                checked={!!newSlide.is_published}
                                                onChange={(e) => setNewSlide((s) => ({ ...s, is_published: e.target.checked }))}
                                            />
                                            Publicado
                                        </label>
                                    </div>
                                    <div>
                                        <Label>Imagem</Label>
                                        <p className="mt-2 text-sm text-muted-foreground">Selecione uma imagem clicando no botão abaixo.</p>
                                        <Button
                                            type="button"
                                            variant="default"
                                            className="mt-2 w-auto bg-black text-white hover:bg-black/90"
                                            onClick={() => {
                                                setImagePickerFor('slide');
                                                setImagePickerOpen(true);
                                            }}
                                        >
                                            Selecionar da galeria
                                        </Button>
                                        <div
                                            className={cn(
                                                'mt-4 aspect-video w-full overflow-hidden rounded-2xl shadow-lg',
                                                !selectedSlideImage && 'border-2 border-dashed',
                                            )}
                                        >
                                            {selectedSlideImage && (
                                                <ImageEditor
                                                    src={selectedSlideImage.url}
                                                    onExport={setEditedSlideBlob}
                                                    sizeClass="w-full"
                                                    aspect="video"
                                                >
                                                    <ImagePreviewOverlay
                                                        titulo={newSlide.title}
                                                        subtitulo={newSlide.subtitle}
                                                        preco={newSlide.price}
                                                        quartos={newSlide.bedrooms}
                                                        banheiros={newSlide.bathrooms}
                                                        area={newSlide.area}
                                                        bairro={newSlide.neighborhood}
                                                    />
                                                </ImageEditor>
                                            )}
                                        </div>
                                    </div>
                                    <div className="flex items-end gap-2">
                                        <Button className="w-auto" onClick={submitSlide} disabled={creatingSlide} title="Adicionar Slide">
                                            {creatingSlide ? '…' : '+'}
                                        </Button>
                                    </div>
                                </div>
                                <DialogFooter>
                                    <Button className="w-auto" variant="secondary" onClick={() => setHeroModalOpen(false)}>
                                        Fechar
                                    </Button>
                                </DialogFooter>
                            </DialogContent>
                        </Dialog>

                        <FeaturedPropertiesModal
                            open={featuredModalOpen}
                            onOpenChange={setFeaturedModalOpen}
                            images={images}
                            featured={featured}
                            onRefreshFeatured={refreshFeatured}
                            onNotice={(n) => setNotice(n)}
                        />
                    </>
                )}
                {/* Dialogo para selecionar imagem para slides */}
                <Dialog
                    open={imagePickerOpen && imagePickerFor === 'slide'}
                    onOpenChange={(o) => {
                        if (!o) {
                            setImagePickerOpen(false);
                            setImagePickerFor(null);
                        }
                    }}
                >
                    <DialogContent aria-describedby="image-picker-slide-desc">
                        <DialogHeader>
                            <DialogTitle>Selecionar imagem</DialogTitle>
                        </DialogHeader>
                        {/* DialogDescription é necessário para acessibilidade */}
                        <DialogDescription id="image-picker-slide-desc">Escolha uma imagem na lista abaixo</DialogDescription>
                        <ImageGallery
                            images={images}
                            onSelect={(img) => {
                                setSelectedSlideImage(img);
                                setNewSlide((s) => ({ ...s, image_id: img.id }));
                                setImagePickerOpen(false);
                                setImagePickerFor(null);
                            }}
                        />
                    </DialogContent>
                </Dialog>

            </div>
        </div>
    );
}
