import ImageEditor from '@/components/ImageEditor';
import ImagePreviewOverlay from '@/components/ImagePreviewOverlay';
import FeaturedCardInfo from '@/components/FeaturedCardInfo';
// import { Heart } from 'lucide-react';
import FeaturedPropertiesModal from '@/components/modals/FeaturedPropertiesModal';
import SlideCard, { type Slide as SlideCardSlide } from '@/components/SlideCard';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { cn } from '@/lib/utils';
import AppLayout from '@/layouts/app-layout';
import { Head } from '@inertiajs/react';
import { apiFetch } from '@/lib/api';
import { ChangeEvent, useEffect, useRef, useState } from 'react';
// Removido CSS legado para manter aparência consistente com as demais views
// import '../../css/oldsite.css';

// Typed route helpers generated by Wayfinder
import * as FeaturedActions from '@/actions/App/Http/Controllers/FeaturedPropertyController';
import * as HeroActions from '@/actions/App/Http/Controllers/HeroSlideController';
import * as ImageActions from '@/actions/App/Http/Controllers/ImageController';
import { type BreadcrumbItem } from '@/types';
import { painel } from '@/routes';

const breadcrumbs: BreadcrumbItem[] = [
    {
        title: 'Painel',
        href: painel().url,
    },
];

type Image = {
    id: number;
    url: string;
    original_name: string;
    filename: string;
    width?: number | null;
    height?: number | null;
};

type HeroSlide = {
    id: number;
    image_id: number;
    image_url?: string | null;
    title: string;
    subtitle?: string | null;
    price: string;
    bedrooms?: number | null;
    bathrooms?: number | null;
    area?: string | null;
    neighborhood?: string | null;
    is_new?: boolean;
    is_published?: boolean;
    position?: number;
};

type FeaturedProperty = {
    id: number;
    image_id: number;
    image_url?: string | null;
    title: string;
    neighborhood?: string | null;
    price: string;
    bedrooms?: number | null;
    bathrooms?: number | null;
    area?: string | null;
    type?: string | null;
    features?: string[];
    price_range?: string | null;
    is_new?: boolean;
    is_published?: boolean;
    position?: number;
    images?: Image[];
};

// api helpers moved to '@/lib/api'

export default function Painel() {
    // Imagens
    const [imagesUploading, setImagesUploading] = useState(false);

    // Slides
    const [slides, setSlides] = useState<HeroSlide[]>([]);
    const [slidesLoading, setSlidesLoading] = useState(false);
    // Local state for legacy slide modal
    const [creatingSlide, setCreatingSlide] = useState(false);
    const [newSlide, setNewSlide] = useState<Partial<HeroSlide>>({});
    const [selectedSlideImage, setSelectedSlideImage] = useState<Image | null>(null);

    // Destaques
    const [featured, setFeatured] = useState<FeaturedProperty[]>([]);
    const [openFeaturedMenu, setOpenFeaturedMenu] = useState<number | null>(null);

    const [dragging, setDragging] = useState<{ type: 'slide' | 'featured'; id: number } | null>(null);
    const [slideOrderDirty, setSlideOrderDirty] = useState(false);
    const [featuredOrderDirty, setFeaturedOrderDirty] = useState(false);

    const [heroModalOpen, setHeroModalOpen] = useState(false);
    const [featuredModalOpen, setFeaturedModalOpen] = useState(false);
    const [editingFeatured, setEditingFeatured] = useState<FeaturedProperty | null>(null);
    const heroUploadInputRef = useRef<HTMLInputElement | null>(null);

    // Notices
    const [notice, setNotice] = useState<{ type: 'success' | 'error'; title: string; message?: string } | null>(null);

    useEffect(() => {
        refreshAll();
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    // Garante tema claro nesta tela (evita fundo preto do modo dark)
    useEffect(() => {
        if (typeof document !== 'undefined') {
            document.documentElement.classList.remove('dark');
        }
    }, []);

    // Masks and formatters
    const formatCurrencyBRLInput = (value: string) => {
        const digits = value.replace(/\D/g, '');
        if (!digits) return '';
        const number = Number(digits) / 100;
        try {
            return number.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
        } catch {
            return `R$ ${number.toFixed(2)}`;
        }
    };

    const formatAreaM2Input = (value: string) => {
        // Mantém apenas dígitos e formata com separador de milhar (pt-BR)
        const digits = value.replace(/\D/g, '');
        if (!digits) return '';
        const n = parseInt(digits, 10);
        try {
            return `${n.toLocaleString('pt-BR')} m²`;
        } catch {
            // Fallback simples
            return `${n} m²`;
        }
    };

    const refreshAll = async () => {
        await Promise.all([refreshSlides(), refreshFeatured()]);
    };

    const refreshSlides = async () => {
        setSlidesLoading(true);
        try {
            const data = await apiFetch<HeroSlide[]>(HeroActions.index());
            setSlides(data);
        } catch (e) {
            setNotice({ type: 'error', title: 'Falha ao carregar slides', message: e instanceof Error ? e.message : String(e) });
        } finally {
            setSlidesLoading(false);
        }
    };

    const refreshFeatured = async () => {
        try {
            const data = await apiFetch<FeaturedProperty[]>(FeaturedActions.index());
            setFeatured(data);
        } catch (e) {
            setNotice({ type: 'error', title: 'Falha ao carregar destaques', message: e instanceof Error ? e.message : String(e) });
        }
    };

    const uploadImages = async (fileList: FileList | null): Promise<Image[]> => {
        if (!fileList || fileList.length === 0) return [];
        const fd = new FormData();
        Array.from(fileList).forEach((f) => fd.append('images[]', f));
        setImagesUploading(true);
        try {
            const uploaded = await apiFetch<Image[]>(ImageActions.store(), { body: fd });
            setNotice({ type: 'success', title: 'Imagens enviadas com sucesso' });
            return uploaded;
        } catch (e) {
            setNotice({
                type: 'error',
                title: 'Falha ao enviar imagens',
                message: e instanceof Error ? e.message : String(e),
            });
            return [];
        } finally {
            setImagesUploading(false);
        }
    };

    const handleHeroUploadChange = async (event: ChangeEvent<HTMLInputElement>) => {
        const uploaded = await uploadImages(event.target.files);
        event.target.value = '';
        if (uploaded.length > 0) {
            const [first] = uploaded;
            setSelectedSlideImage(first);
            setNewSlide((s) => ({ ...s, image_id: first.id }));
        }
    };

    const submitSlide = async () => {
        if (!selectedSlideImage?.id || !newSlide.title || !newSlide.price) {
            alert('Selecione uma imagem, título e preço.');
            return;
        }
        setCreatingSlide(true);
        try {
            const body = JSON.stringify({
                image_id: selectedSlideImage.id,
                title: newSlide.title,
                subtitle: newSlide.subtitle ?? null,
                price: newSlide.price,
                bedrooms: newSlide.bedrooms ?? null,
                bathrooms: newSlide.bathrooms ?? null,
                area: newSlide.area ?? null,
                neighborhood: newSlide.neighborhood ?? null,
                is_new: !!newSlide.is_new,
                is_published: newSlide.id ? !!newSlide.is_published : true,
            });
            if (newSlide.id) {
                await apiFetch(HeroActions.update({ heroSlide: newSlide.id }), {
                    body,
                    headers: { 'Content-Type': 'application/json' },
                });
                setNotice({ type: 'success', title: 'Slide atualizado' });
            } else {
                await apiFetch(HeroActions.store(), {
                    body,
                    headers: { 'Content-Type': 'application/json' },
                });
                setNotice({ type: 'success', title: 'Slide adicionado' });
            }
            setNewSlide({});
            setSelectedSlideImage(null);
            await refreshSlides();
        } finally {
            setCreatingSlide(false);
        }
    };

    const toggleSlidePublish = async (id: number) => {
        await apiFetch(HeroActions.togglePublish({ heroSlide: id }));
        await refreshSlides();
    };

    const deleteSlide = async (id: number) => {
        if (!confirm('Excluir este slide?')) return;
        await apiFetch(HeroActions.destroy({ heroSlide: id }));
        await refreshSlides();
    };

    const editSlide = (slide: SlideCardSlide) => {
        const fullSlide = slides.find((item) => item.id === slide.id) ?? null;
        if (fullSlide) {
            setNewSlide(fullSlide);
            setSelectedSlideImage(
                fullSlide.image_id && fullSlide.image_url
                    ? { id: fullSlide.image_id, url: fullSlide.image_url, original_name: '', filename: '' }
                    : null,
            );
        } else {
            setNewSlide({
                id: slide.id,
                title: slide.title,
                price: slide.price,
                image_id: slide.image_id,
                is_published: slide.is_published,
            });
            setSelectedSlideImage(
                slide.image_id && slide.image_url
                    ? { id: slide.image_id, url: slide.image_url, original_name: '', filename: '' }
                    : null,
            );
        }
        setHeroModalOpen(true);
    };

    const reorderList = <T extends { id: number }>(list: T[], sourceId: number, targetId: number): T[] | null => {
        const next = list.slice();
        const fromIndex = next.findIndex((item) => item.id === sourceId);
        const toIndex = next.findIndex((item) => item.id === targetId);
        if (fromIndex === -1 || toIndex === -1 || fromIndex === toIndex) return null;
        const [moved] = next.splice(fromIndex, 1);
        next.splice(toIndex, 0, moved);
        return next;
    };

    const persistSlidesOrder = async () => {
        const ids = slides.map((s) => s.id);
        if (ids.length === 0) return;
        try {
            await apiFetch(HeroActions.reorder.patch(), {
                body: JSON.stringify({ ids }),
                headers: { 'Content-Type': 'application/json' },
            });
        } catch (e) {
            setNotice({
                type: 'error',
                title: 'Falha ao reordenar slides',
                message: e instanceof Error ? e.message : String(e),
            });
            await refreshSlides();
        } finally {
            setSlideOrderDirty(false);
        }
    };

    const persistFeaturedOrder = async () => {
        const ids = featured.map((f) => f.id);
        if (ids.length === 0) return;
        try {
            await apiFetch(FeaturedActions.reorder.patch(), {
                body: JSON.stringify({ ids }),
                headers: { 'Content-Type': 'application/json' },
            });
        } catch (e) {
            setNotice({
                type: 'error',
                title: 'Falha ao reordenar destaques',
                message: e instanceof Error ? e.message : String(e),
            });
            await refreshFeatured();
        } finally {
            setFeaturedOrderDirty(false);
        }
    };

    const deleteFeatured = async (id: number) => {
        if (!confirm('Excluir este destaque?')) return;
        await apiFetch(FeaturedActions.destroy({ featuredProperty: id }));
        await refreshFeatured();
    };

    const editFeatured = (item: FeaturedProperty) => {
        setEditingFeatured(item);
        setFeaturedModalOpen(true);
    };

    const handleDragEnd = async () => {
        if (!dragging) return;
        const currentDrag = dragging;
        setDragging(null);
        if (currentDrag.type === 'slide') {
            if (slideOrderDirty) await persistSlidesOrder();
        } else if (currentDrag.type === 'featured') {
            if (featuredOrderDirty) await persistFeaturedOrder();
        }
    };

    return (
        <AppLayout breadcrumbs={breadcrumbs}>
            <Head title="Painel" />

            <main className="mx-auto flex w-full max-w-7xl flex-1 flex-col gap-6 px-4 py-8 sm:px-6 lg:px-8">
                {notice && (
                    <Alert variant={notice.type === 'error' ? 'destructive' : 'default'}>
                        <AlertTitle>{notice.title}</AlertTitle>
                        {notice.message && <AlertDescription>{notice.message}</AlertDescription>}
                    </Alert>
                )}
                {/* Hero Slides */}
                <>
                        {/* Seção: Hero Slides */}
                        <div className="mb-2 flex flex-wrap items-center justify-between gap-2">
                            <div className="flex items-center gap-2">
                                <button
                                    type="button"
                                    className="flex items-center gap-2 text-lg font-semibold hover:underline"
                                    onClick={() => {
                                        setNewSlide({});
                                        setSelectedSlideImage(null);
                                        setHeroModalOpen(true);
                                    }}
                                    title="Novo Slide"
                                >
                                    <span className="inline-flex h-7 w-7 items-center justify-center rounded-full bg-black text-white">+</span>
                                    <span>Hero Slides</span>
                                </button>
                            </div>
                            {/* Botão de atualizar removido */}
                        </div>

                        <div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
                            {slides.map((s) => (
                                <div
                                    key={s.id}
                                    draggable
                                    onDragStart={(event) => {
                                        event.dataTransfer.effectAllowed = 'move';
                                        event.dataTransfer.setData('text/plain', String(s.id));
                                        setDragging({ type: 'slide', id: s.id });
                                    }}
                                    onDragEnter={() => {
                                        if (!dragging || dragging.type !== 'slide' || dragging.id === s.id) return;
                                        setSlides((prev) => {
                                            const updated = reorderList(prev, dragging.id, s.id);
                                            if (!updated) return prev;
                                            setSlideOrderDirty(true);
                                            return updated;
                                        });
                                    }}
                                    onDragOver={(event) => {
                                        if (!dragging || dragging.type !== 'slide') return;
                                        event.preventDefault();
                                        event.dataTransfer.dropEffect = 'move';
                                    }}
                                    onDrop={(event) => {
                                        if (!dragging || dragging.type !== 'slide') return;
                                        event.preventDefault();
                                    }}
                                    onDragEnd={handleDragEnd}
                                    className={cn(
                                        'cursor-move select-none',
                                        dragging?.type === 'slide' && dragging.id === s.id ? 'ring-2 ring-primary ring-offset-2' : '',
                                    )}
                                >
                                    <SlideCard slide={s} onEdit={editSlide} onToggle={toggleSlidePublish} onDelete={deleteSlide} />
                                </div>
                            ))}
                        </div>

                        {/* Seção: Imóveis em Destaque */}
                        <div className="mt-10 mb-2 flex flex-wrap items-center justify-between gap-2">
                            <div
                                className="flex items-center gap-2"
                            >
                                <button
                                    type="button"
                                    className="inline-flex h-7 w-7 items-center justify-center rounded-full bg-black text-white"
                                    onClick={() => { setEditingFeatured(null); setFeaturedModalOpen(true); }}
                                    title="Novo Destaque"
                                >
                                    +
                                </button>
                                <h2 className="text-lg font-semibold cursor-pointer hover:underline" onClick={() => { setEditingFeatured(null); setFeaturedModalOpen(true); }}>Imóveis em Destaque</h2>
                                
                            </div>
                            {/* Botão de atualizar removido */}
                        </div>
                        <div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
                            {featured.map((f) => {
                                const bedrooms = typeof f.bedrooms === 'number' ? f.bedrooms : undefined;
                                const bathrooms = typeof f.bathrooms === 'number' ? f.bathrooms : undefined;
                                const features = Array.isArray(f.features)
                                    ? f.features.filter((feature): feature is string => typeof feature === 'string')
                                    : [];

                                return (
                                    <div
                                        key={f.id}
                                        draggable
                                        onDragStart={(event) => {
                                            event.dataTransfer.effectAllowed = 'move';
                                            event.dataTransfer.setData('text/plain', String(f.id));
                                            setDragging({ type: 'featured', id: f.id });
                                        }}
                                        onDragEnter={() => {
                                            if (!dragging || dragging.type !== 'featured' || dragging.id === f.id) return;
                                            setFeatured((prev) => {
                                                const updated = reorderList(prev, dragging.id, f.id);
                                                if (!updated) return prev;
                                                setFeaturedOrderDirty(true);
                                                return updated;
                                            });
                                        }}
                                        onDragOver={(event) => {
                                            if (!dragging || dragging.type !== 'featured') return;
                                            event.preventDefault();
                                            event.dataTransfer.dropEffect = 'move';
                                        }}
                                        onDrop={(event) => {
                                            if (!dragging || dragging.type !== 'featured') return;
                                            event.preventDefault();
                                        }}
                                        onDragEnd={handleDragEnd}
                                        className={cn(
                                            'property-card bg-white rounded-2xl shadow-lg overflow-hidden cursor-move select-none',
                                            dragging?.type === 'featured' && dragging.id === f.id
                                                ? 'ring-2 ring-primary ring-offset-2'
                                                : '',
                                        )}
                                    >
                                        <div className="relative">
                                            <div className="h-64 overflow-hidden">
                                                {f.image_url ? (
                                                    <img
                                                        src={f.image_url}
                                                        alt={f.title}
                                                        className="h-full w-full object-cover transition-transform duration-300 hover:scale-105"
                                                    />
                                                ) : (
                                                    <div className="h-full w-full bg-muted" />
                                                )}
                                            </div>
                                            <div className="absolute left-4 top-4 flex gap-2">
                                                {!!f.is_new && (
                                                    <span className="rounded-full bg-primary px-3 py-1 text-xs font-semibold text-white">Novo</span>
                                                )}
                                                {(f.neighborhood ?? '').toString().trim() && (
                                                    <span className="rounded-full bg-white/90 px-3 py-1 text-xs font-medium text-gray-900 backdrop-blur-sm">
                                                        {f.neighborhood}
                                                    </span>
                                                )}
                                            </div>
                                            {/* Botão de menu (canto superior direito) */}
                                            <button
                                                type="button"
                                                className="absolute right-4 top-4 z-10 flex h-9 w-9 items-center justify-center rounded-full bg-black/60 text-white backdrop-blur-sm hover:bg-black"
                                                aria-label="Menu"
                                                onClick={(e) => {
                                                    e.stopPropagation();
                                                    setOpenFeaturedMenu((v) => (v === f.id ? null : f.id));
                                                }}
                                            >
                                                ⋮
                                            </button>
                                            {openFeaturedMenu === f.id && (
                                                <div className="absolute right-4 top-14 z-20 w-36 overflow-hidden rounded-lg border bg-white shadow-lg">
                                                    <button
                                                        type="button"
                                                        className="block w-full px-3 py-2 text-left text-sm hover:bg-muted"
                                                        onClick={() => {
                                                            setOpenFeaturedMenu(null);
                                                            editFeatured(f);
                                                        }}
                                                    >
                                                        Editar
                                                    </button>
                                                    <button
                                                        type="button"
                                                        className="block w-full px-3 py-2 text-left text-sm text-red-600 hover:bg-muted"
                                                        onClick={() => {
                                                            setOpenFeaturedMenu(null);
                                                            deleteFeatured(f.id);
                                                        }}
                                                    >
                                                        Excluir
                                                    </button>
                                                </div>
                                            )}
                                            {/* Botão de favorito removido */}
                                        </div>
                                        <FeaturedCardInfo
                                            title={f.title}
                                            neighborhood={f.neighborhood}
                                            bedrooms={bedrooms}
                                            bathrooms={bathrooms}
                                            area={f.area ?? undefined}
                                            features={features}
                                            price={f.price}
                                        />
                                    </div>
                                );
                            })}
                        </div>

                        <Dialog open={heroModalOpen} onOpenChange={setHeroModalOpen}>
                            <DialogContent className="w-full sm:max-w-5xl" aria-describedby="hero-slides-desc">
                                <DialogHeader>
                                    <div className="flex items-center justify-between">
                                        <DialogTitle>Hero Slides</DialogTitle>
                                        <div className="flex items-center gap-2 text-sm text-muted-foreground">
                                            <span>{slidesLoading ? 'Carregando…' : `${slides.length} itens`}</span>
                                            <Button
                                                className="hidden w-auto bg-black text-white hover:bg-black/80"
                                                variant="secondary"
                                                onClick={refreshSlides}
                                                disabled={slidesLoading}
                                                title="Atualizar"
                                            >
                                                ↻
                                            </Button>
                                        </div>
                                    </div>
                                </DialogHeader>
                                <DialogDescription id="hero-slides-desc">
                                    Preencha os dados e selecione uma imagem para criar ou editar um slide do hero.
                                </DialogDescription>
                                <div className="space-y-4">
                                    <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-4">
                                        <div>
                                            <Label>Título</Label>
                                            <Input
                                                value={newSlide.title ?? ''}
                                                onChange={(e) => setNewSlide((s) => ({ ...s, title: e.target.value }))}
                                                placeholder="Ex: Casa moderna no Setor Marista"
                                            />
                                        </div>
                                        <div>
                                            <Label>Subtítulo</Label>
                                            <Input
                                                value={newSlide.subtitle ?? ''}
                                                onChange={(e) => setNewSlide((s) => ({ ...s, subtitle: e.target.value }))}
                                                placeholder="Ex: Próximo ao Flamboyant"
                                            />
                                        </div>
                                        <div>
                                            <Label>Bairro</Label>
                                            <Input
                                                value={newSlide.neighborhood ?? ''}
                                                onChange={(e) => setNewSlide((s) => ({ ...s, neighborhood: e.target.value }))}
                                                placeholder="Ex: Setor Marista"
                                            />
                                        </div>
                                        <div>
                                            <Label>Preço</Label>
                                            <Input
                                                value={newSlide.price ?? ''}
                                                onChange={(e) => setNewSlide((s) => ({ ...s, price: formatCurrencyBRLInput(e.target.value) }))}
                                                inputMode="numeric"
                                                placeholder="Ex: R$ 1.250.000,00"
                                            />
                                        </div>
                                    </div>
                                    <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
                                        <div>
                                            <Label>Quartos</Label>
                                            <Input
                                                type="number"
                                                min={0}
                                                value={newSlide.bedrooms ?? ''}
                                                onChange={(e) => setNewSlide((s) => ({ ...s, bedrooms: Number(e.target.value || 0) }))}
                                                inputMode="numeric"
                                                placeholder="Ex: 3"
                                            />
                                        </div>
                                        <div>
                                            <Label>Banheiros</Label>
                                            <Input
                                                type="number"
                                                min={0}
                                                value={newSlide.bathrooms ?? ''}
                                                onChange={(e) => setNewSlide((s) => ({ ...s, bathrooms: Number(e.target.value || 0) }))}
                                                inputMode="numeric"
                                                placeholder="Ex: 2"
                                            />
                                        </div>
                                        <div>
                                            <Label>Área</Label>
                                            <Input
                                                value={newSlide.area ?? ''}
                                                onChange={(e) => setNewSlide((s) => ({ ...s, area: formatAreaM2Input(e.target.value) }))}
                                                inputMode="numeric"
                                                placeholder="Ex: 120 m²"
                                            />
                                        </div>
                                    </div>
                                    <div className="flex items-center gap-6">
                                        <label className="flex items-center gap-2 text-sm">
                                            <input
                                                type="checkbox"
                                                checked={!!newSlide.is_new}
                                                onChange={(e) => setNewSlide((s) => ({ ...s, is_new: e.target.checked }))}
                                            />
                                            Novo
                                        </label>
                                        {/* Checkbox "Publicado" removido: novos slides serão publicados automaticamente */}
                                    </div>
                                    <div>
                                        <Label>Imagem</Label>
                                        <p className="mt-2 text-sm text-muted-foreground">Envie uma imagem utilizando o botão abaixo.</p>
                                        <Button
                                            type="button"
                                            variant="secondary"
                                            className="mt-2 w-auto bg-black text-white hover:bg-black/80"
                                            onClick={() => heroUploadInputRef.current?.click()}
                                            disabled={imagesUploading}
                                        >
                                            {imagesUploading ? 'Enviando…' : 'Enviar imagem'}
                                        </Button>
                                        <input
                                            ref={heroUploadInputRef}
                                            type="file"
                                            multiple
                                            accept="image/*"
                                            className="hidden"
                                            onChange={handleHeroUploadChange}
                                        />
                                        <div
                                            className={cn(
                                                'mt-4 aspect-video w-full overflow-hidden rounded-2xl shadow-lg',
                                                !selectedSlideImage && 'border-2 border-dashed',
                                            )}
                                        >
                                            {selectedSlideImage && (
                                                <ImageEditor src={selectedSlideImage.url} sizeClass="w-full" aspect="video">
                                                    <ImagePreviewOverlay
                                                        titulo={newSlide.title}
                                                        subtitulo={newSlide.subtitle}
                                                        preco={newSlide.price}
                                                        quartos={newSlide.bedrooms}
                                                        banheiros={newSlide.bathrooms}
                                                        area={newSlide.area}
                                                        bairro={newSlide.neighborhood}
                                                    />
                                                </ImageEditor>
                                            )}
                                        </div>
                                    </div>
                                </div>
                                <DialogFooter>
                                    <Button className="w-auto bg-black text-white hover:bg-black/80" variant="secondary" onClick={() => setHeroModalOpen(false)}>
                                        Fechar
                                    </Button>
                                    <Button className="w-auto" onClick={submitSlide} disabled={creatingSlide} title="Adicionar Slide">
                                        {creatingSlide ? 'Publicando.' : 'Publicar'}
                                    </Button>
                                </DialogFooter>
                            </DialogContent>
                        </Dialog>

                        <FeaturedPropertiesModal
                            open={featuredModalOpen}
                            onOpenChange={(open) => {
                                setFeaturedModalOpen(open);
                                if (!open) setEditingFeatured(null);
                            }}
                            featured={featured}
                            onRefreshFeatured={refreshFeatured}
                            onNotice={(n) => setNotice(n)}
                            onUploadImages={uploadImages}
                            uploadingImages={imagesUploading}
                            editing={editingFeatured}
                        />
                </>

            </main>
        </AppLayout>
    );
}

