# .github/workflows/tests.yml
name: tests
on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
          coverage: none

      - name: Install PHP deps
        run: composer install --no-interaction --prefer-dist --no-progress

      # <<< preparar Laravel ANTES do build >>>
      - name: Copy Environment File
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Generate Application Key
        run: php artisan key:generate
      # ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Node deps
        run: npm ci

      - name: Build Assets
        run: npm run build

      - name: Tests
        run: php artisan test
