name: tests
on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: composer

      - name: Install PHP deps
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Generate APP key
        run: php artisan key:generate

      # evita depender de MySQL no runner:
      - name: Set testing env (SQLite in-memory)
        run: |
          php -r 'file_put_contents(".env", PHP_EOL."APP_ENV=testing", FILE_APPEND);'
          php -r 'file_put_contents(".env", PHP_EOL."DB_CONNECTION=sqlite", FILE_APPEND);'
          php -r 'file_put_contents(".env", PHP_EOL."DB_DATABASE=:memory:", FILE_APPEND);'

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Node deps
        run: npm ci

      - name: Build assets (Vite)
        run: npm run build

      - name: Run tests
        run: php artisan test
